apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web
  name: web
spec:
  containers:
  - image: nginx
    name: web
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}




# generate skeleton 
# kubectl run web --image=nginx --dry-run=client -o yaml \
#   > manifests/web-pod.yaml